# LighthouseでCWVスコア測定を行う
name: Lighthouse CI

# 手動トリガー
on: [ workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run Lighthouse 
        run: |
          npm init -y
          npm install -g @lhci/cli@0.8.x
          lhci collect --url='http://example.com'
